### ISSUE TITLE
questions about the data size

### ISSUE THREAD

**Issue by happyday521** [Zhangjinso/PISE#14]
Great work！I have some questions about the data size.
1、In my opinion, the loadsize of input image, pose map, and parsing map is all 256x256 in your method.  However, the key points annotations are obtained from the cropped images with the resolution of 176x256, which means the oldsize should be 176x256. However, why  do you set  **parser.set_defaults(old_size=(256, 256))** in fashion_dataset.py ?
2、Your parsing maps are obtained from the cropped images with the resolution of 176x256, and then padding to 256X256. Is it right?
3、The original images of DeepFashion dataset(256x256)  have the backgrounds with inconsistent colors. Will it have a bad effect when used directly for training? Need I crop them to 176x256, and then padding them to 256X256？
![image](https://user-images.githubusercontent.com/35884085/114861850-6674ba00-9e20-11eb-8bdf-f3bab331ae53.png)
Thanks very much!

**Comment by Zhangjinso** [comment]
Thanks for your interesting. 
1. The pose annotations is from global flow  local attention. They get it using 256X256 images  resized from 256X176. To confirm the consistents，you can draw it by adding 'input_BP2' to line50 in model/painet.py. 
2. In fact, it is useless to this project. It was generated during debugging...
3. The backgrounds are not complex, so I think it will not affect the model seriously.

**Comment by happyday521** [comment]
Thanks for your reply! One more question, in your paper, do the PSNR and FID score are all directly calculated upon the generated images with the resolution of 256x256?  Need it to crop or resize them? 
Thank you very much!

**Comment by Zhangjinso** [comment]
Sorry for the delay. We test PSNR with the resolution of 256X176 and FID with the resolution of 256X256. The generated images are first cropped to 256X176 which the resolution is 256X256 except for GFLA, and then padded to 256X256. For the results of GFLA, due to the input and the output are 256X256 of the person region, we first resize the images to 256X176 and then compute the metrics.

**Comment by happyday521** [comment]
Got it！Thanks very much.
