### ISSUE TITLE
Regarding paper 

### ISSUE THREAD

**Issue by Abhijithchintu** [Zhangjinso/PISE#15]
Tried to read your paper , it is tough to follow , like what is decoupled gan , is it a type of gan , if it is then there was nothing mentioned about discriminator . I couldnt find any search result on decoupled gan . Are there any video explanations of your paper ,or regarding decoupled gan. If they are there can you please share

**Comment by Zhangjinso** [comment]
The decoupled GAN means disentangle the shape and the style of clothing, which is also the motivation for the whole work (e.g., two-stage framework, per-region encoding and normalization) to achieve a flexible editing. The intro and the contributions that we summarized have mentioned this. BTW, The supp. was already in the ReadMe.
