### ISSUE TITLE
a question about the code

### ISSUE THREAD

**Issue by happyday521** [Zhangjinso/PISE#16]
I have a question about the code.  In my opinion, as shown in the Fig, the code from line 627-638 should be aligned with the line 605. 
In other words,  I think you should first finish the for loop about b_size to obtain the middle_avg before performing subsequent operations. Please check it. Thanks!
![image](https://user-images.githubusercontent.com/35884085/115492993-7c0d3800-a295-11eb-8849-2387d1d80b8f.png)

**Comment by Zhangjinso** [comment]
Wow, you are right! Maybe it is produced when I am sleeping, who knows. Thanks for pointing this out. It can decrease the training speed, but it will not affect the final results. Anyway, thanks for your help.

**Comment by happyday521** [comment]
:)
