### ISSUE TITLE
The metric

### ISSUE THREAD

**Issue by zwy1996** [Zhangjinso/PISE#18]
Hi, nice job!

I was sorry to bother you, when I used the test instruction， I can get the eval_results. I was a little confused to get the results as your paper. May I use other calculate the metric program?

Thank you very much!

**Comment by Zhangjinso** [comment]
Hi, if the testing results are abnormal, you can test again after revising the old_size in line 18 of data/fashion_data.py to (256, 176) to verify this.  For the other calculate the metric program, I am not sure what is the question about. If you would like to use other metrics, of course, it is ok.

**Comment by zwy1996** [comment]
Hi
Thanks for your response in time.
Maybe I did not describe the problem correctly. I mean that I can not get the quantitative results just like your paper ( 13.61 0.2059 31.38) when I used the test instruction, I get nothing.

Thank you.

**Comment by Zhangjinso** [comment]
I do not combine the scripts of the score in the current project. The fid and lpips  score are computed by the official pytorch version of them, and the psnr is implemented to be obtain. Maybe add that soon.

**Comment by zwy1996** [comment]
OK，

Thank you very much!!!
