### ISSUE TITLE
ModuleNotFoundError: No module named 'dominate'

### ISSUE THREAD

**Issue by sshlvn** [Zhangjinso/PISE#19]
Good day!

I tried to run 

> python test.py --name=fashion --model=painet --gpu_ids=0

but I got 

> ModuleNotFoundError: No module named 'dominate'

in html.py file https://github.com/Zhangjinso/PISE/blob/f9dfacb16db99420a5a51bf7e0fd2a632466b701/util/html.py#L1

Can you help me please?

**Comment by sshlvn** [comment]
I'm sorry I missed

> pip install dominate

**Comment by PabloGP88** [comment]
a
