### ISSUE TITLE
What is the mapping of the semantic map of person image to the merged K=8 attribute?

### ISSUE THREAD

**Issue by imzhangsheng** [Zhangjinso/PISE#2]
Could you kindly tell me how to map 20 different attributes into K=8 attributes.

The current indexes are 'Hat', 'Hair', 'Glove', 'Sunglasses', 'Upper Clothes', 'Dress', 'Coat', 'Socks', 'Pants', 'Jumpsuits', 'Scarf', 'Skirt', 'Face', 'Left-arm', 'Right-arm', 'Left-leg', 'Right-leg', 'Left-shoe' and 'Right-shoe'.

And the merged indexes mentioned in your paper are 'Hair', 'Upper Clothes', 'Dress', 'Pants', 'Face', 'Upper skin', 'leg' and 'background'.

**Comment by Zhangjinso** [comment]
Hi, for example, 'right arm', 'left arm' can be combined into 'upper skin'. You can decode our parsing data followed by https://github.com/Engineering-Course/CIHP_PGN/blob/master/utils/utils.py to see the organization of it. The detailed correspondence is that :
from_label = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17 , 18, 19, 20]
to_label =   [0, 1, 1, 0, 0, 2, 3, 2, 7, 3, 6,  0,  3,  5,  6,   6,  7,  7,   4,  4, 0]. 
You can organize it as you like.
