### ISSUE TITLE
About the accurate correspondences between different parsing labels and indexes in your provided parsing data

### ISSUE THREAD

**Issue by happyday521** [Zhangjinso/PISE#20]
Hi! 
Could you tell me the accurate correspondences between different parsing labels and indexes in your provided parsing data? 
The parsing labels mentioned in your paper are 'Hair', 'Upper Clothes', 'Dress', 'Pants', 'Face', 'Upper skin', 'leg' and 'background', which seems differs from that in your provided parsing data. 
For example, in your provided parsing data, you set the 'Shoes' to a separate category，meanwhile combine the arm and leg skins into the same category.
![image](https://user-images.githubusercontent.com/35884085/117260430-a825dd00-ae81-11eb-9a26-237b13ba1e55.png)

Besides, when I visualize your provided parsing data, the area of region with index == 1 seems always equal to 0. Please check it.
PS: I don't solve my problem from the similar issue like #2 

Thanks!

**Comment by Zhangjinso** [comment]
Hi.
After checking the organization of the data, the correspondences are ['0': background, '1': hat, '2': hair, '3':upper clothes, '4': lower part of the body, '5': lower part of the body, '6': skin, '7' face]. This will be corrected in the next version of our paper. 
BTW, how to re-organize the labels to the limited categories of parsing (for efficiency) is worth discussing. The pose can help distinguish the legs and the arms, so I think it may be more reasonable. Therefore, in my opinion, if the labels are reasonable, you can re-organize it as you like to deal with.

**Comment by happyday521** [comment]
Thanks for your reply. However, to be more precise, I think '4' should be 'Shoes(including socks)', while '5' should be 'lower clothes(e.g. pants, shorts)'.  Regarding them all as 'lower part of the body' may be not reasonable.
![image](https://user-images.githubusercontent.com/35884085/117389450-fa690b80-af1e-11eb-8079-d8d0a9dcfa50.png)

**Comment by Zhangjinso** [comment]
Yeap, 4 is represented as shoes (and socks). It is a typo error in the previous reply.
