### ISSUE TITLE
A question about the paper

### ISSUE THREAD

**Issue by Mathilda88** [Zhangjinso/PISE#22]
First thank you for the great job and sharing it with the community,

I have a question about the pipeline of the method. As I noticed the training procedure needs to be done in two different stages, one for generating the parsing map and then after for generating the final image. So my question is does the second stage provide any kind of gradients for the first one, or not these two steps are quite disconnected from each other?

Thank you in advance

**Comment by Zhangjinso** [comment]
Hi,
if you run the current generator, the image generator can provide the gradients for the parsing generator. But if you uncomment line 162-176 and comment line 177 and 178 in 'generator.py', these two steps are disconnected due to some non-differentiable operations (e.g., argmax).

**Comment by Mathilda88** [comment]
Thanks for the response
