### ISSUE TITLE
The correspondence loss is actually not used

### ISSUE THREAD

**Issue by imbinwang** [Zhangjinso/PISE#27]
Hi,

The correspondence loss of image generator in paper section 3.3 is not used in  your [code](https://github.com/Zhangjinso/PISE/blob/main/model/painet_model.py#L47).

> self.loss_names = [ 'app_gen','content_gen', 'style_gen', #'reg_gen',
                           'ad_gen', 'dis_img_gen', 'par', 'par1']

Does the correspondence loss not impact the final generated image? Thanks for your reply.

**Comment by Zhangjinso** [comment]
This is because we first trained the model with correspondence loss with “False" flag for spatio-aware module. Then we trained the spatio-aware module without this loss.

**Comment by imbinwang** [comment]
Thank for your clarification. As I understand, you means the training process consist of two steps:
  1. train the model with correspondence loss but without spatio-aware module,
  2. finetune the model saved in step1 with spatio-aware module but without correspondence loss.

Do you train the whole model in a process? It seems a valid choice.

**Comment by Zhangjinso** [comment]
The correspondence loss is used to bridge the gap between the source image and the target image in different poses. This is for computing the correspondence of these two features. You can check [cocosnet](https://arxiv.org/abs/2004.05571). Though these two features do not have large gaps, but we use it to obtain a more precise correspondences. In fact, if do not consider the training time, you can train using  spatio-aware module with the correspondence loss.

**Comment by imbinwang** [comment]
I will try it. Thank you.
