### ISSUE TITLE
How to edit the parsing map

### ISSUE THREAD

**Issue by happyday521** [Zhangjinso/PISE#28]
Hi, for region editing, gievn a certain parsing map, how do you edit it to obtain the desired parsing maps？Can you share the scripts or tools you used? Thanks!

**Comment by Zhangjinso** [comment]
You can write a ui by PyQT based on [which I used](https://github.com/HAN-YANG-HIT/Fashion-Editing.git) or [this](https://github.com/stevliu/editnerf.git). The ui modified by me is lost and maybe re-write and share it when I am free.

**Comment by happyday521** [comment]
Got it. Thanks!
