### ISSUE TITLE
Do you have a trained model?

### ISSUE THREAD

**Issue by freedom521jin** [Zhangjinso/PISE#29]
I want to only test and i don't have any gpus,so,please provide a model that can be used to test？
Thx a lot!

**Comment by Zhangjinso** [comment]
I think you can modified the [set input function](https://github.com/Zhangjinso/PISE/blob/f9dfacb16db99420a5a51bf7e0fd2a632466b701/model/painet_model.py#L96) to change the inputs from 'cuda' to 'cpu' and test as before to get the results (refer to [this](https://github.com/Zhangjinso/PISE/blob/f9dfacb16db99420a5a51bf7e0fd2a632466b701/model/base_model.py#L193). ).

Hope this can help you~

**Comment by freedom521jin** [comment]
> I think you can modified the [set input function](https://github.com/Zhangjinso/PISE/blob/f9dfacb16db99420a5a51bf7e0fd2a632466b701/model/painet_model.py#L96) to change the inputs from 'cuda' to 'cpu' and test as before to get the results (refer to [this](https://github.com/Zhangjinso/PISE/blob/f9dfacb16db99420a5a51bf7e0fd2a632466b701/model/base_model.py#L193). ).
> 
> Hope this can help you~

Thx, I can test with cpu.And , I have trained the model ,follew your steps ,but some evel results are not very satisfactory ，the model has been trained for one week by GPU-1080Ti.Then, I download your evel results,and some results that I test by my model are bad too . So I hope you can provide your model that trained already.Thx!

**Comment by Zhangjinso** [comment]
The checkpoint used in our paper was released in ReadMe. 

Pre-trained checkpoint of human pose transfer reported in our paper can be found from [baidu](https://pan.baidu.com/s/14v3LaCCGCHJUoqQ_wlyNpA) (fetch code: abcd) or [Google drive](https://drive.google.com/file/d/1gcdzahJ-pE-bSQfcnrW__iXIViH_y-FB/view?usp=sharing) and put it in the folder (-->results-->fashion).
