### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by yyxYIN** [Zhangjinso/PISE#3]
作者你好，我最近看了你的这篇论文很受启发，我想复现一下你的代码，你的训练数据集有提供吗，Readme里好像没有说明白。

**Comment by Zhangjinso** [comment]
Hi, as presented in our paper, the data for training consists of paired images and keypoints of them, which can be found in https://github.com/tengteng95/Pose-Transfer. Besides, the parsing data is also needed, which is available in the ReadMe in Baidu Disk or Google Drive.

**Comment by Zhangjinso** [comment]
The ReadMe has updated, please check  it.
