### ISSUE TITLE
模型复现不了的问题

### ISSUE THREAD

**Issue by zgs731** [Zhangjinso/PISE#31]
你好

在使用README.md中的"Pre-trained checkpoint of human pose transfer"预测时，和你提供的预测结果不一样，效果比较差，请问是什么原因？除了把模型放到指定路径，还需要别的设置吗？

我在使用自己训练的模型时，效果还是可以的。

最后想问 有可以直接迁移任意一张图像的demo吗？

非常感谢

**Comment by Zhangjinso** [comment]
测试结果可能是因为[这个问题](https://github.com/Zhangjinso/PISE/issues/21#issuecomment-839797211)。
demo暂时没有做，如果想测试的话，可以先参考这个[issue](https://github.com/Zhangjinso/PISE/issues/5#issuecomment-808134948)。
