### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by MLAdicct** [Zhangjinso/PISE#36]
Hi,
I have read your paper and tried to implement it. But in order for it to be used for virtual try onns I tried to take this project to next level by adding a person identification of generated image in new pose with respect to the real image of the same person in order to calculate the final accuracy of the model??
So can you give me any idea on how to approach this?

**Comment by Zhangjinso** [comment]
Sorry, I don't know if I understand what you mean.
Like many virtual try-on methods, you can first generate a target parsing, then use a warp module to reatain the details and the per-region normalization with target style to refine the feature to predict reasonable style, especially for invisible regions. 
Hope that can help you.
