### ISSUE TITLE
how to visualize the parsing map?

### ISSUE THREAD

**Issue by Jerric-wu** [Zhangjinso/PISE#38]

**Comment by Zhangjinso** [comment]
You can refer to [that](https://github.com/Zhangjinso/PISE/issues/21#issuecomment-841909567)

**Comment by Jerric-wu** [comment]
> You can refer to [that](https://github.com/Zhangjinso/PISE/issues/21#issuecomment-841909567)
Thank you very much for your reply, I still have a question is that how to calculate the LPIPS. What do the ground-truth images and the generated images referring?  Are the generated images from training or the 'eval_results', if come from 'eval_result', what are the corresponding ground-truth images? Look forward to your reply, thanks.
