### ISSUE TITLE
 I couldn't find the code locations that to "comments the line 177 and 178, and uncomments line 162-176."  mentioned in README.

### ISSUE THREAD

**Issue by dyyzb** [Zhangjinso/PISE#41]
Hi Jinsong, I'm really interest in PISE and admire your work. 
At your convenience, I'd like to confirm with you about the code locations that to "comments the line 177 and 178, and uncomments line 162-176." mentioned in the Train sector of README because I couldn't find these two pieces of code and I really want to study them.
Looking forward to your reply. Thanks a lot!

**Comment by Zhangjinso** [comment]
you can find that in the [generator file](https://github.com/Zhangjinso/PISE/blob/e1972cce23b59699a37e187f34ccaaa78de522a1/model/networks/generator.py#L162)

**Comment by dyyzb** [comment]
I am very grateful for your reply. 
Also, I would like to ask if the training deadline is when the number of iterations reaches the threshold, and what is the approximate duration of model training.
I really hope to receive your reply。

**Comment by Zhangjinso** [comment]
You can try it using the same parameters in other methods, e.g., 200 epochs. I remember I trained the model about 70k-80k iters on a single 2080Ti card.

**Comment by dyyzb** [comment]
Thank you very much for your reply. I also trained on 2080, with a set iteration count of 50k.
