### ISSUE TITLE
Another dataset

### ISSUE THREAD

**Issue by RominaZakerian** [Zhangjinso/PISE#42]
hi. thanks for your great work. how can I use this code for another person dataset to generate persons in new poses? for example "Market1501" dataset. that is the dataset using for person re-identification.

**Comment by Zhangjinso** [comment]
Thanks for your interest. If you want to run our code for Market1501, you should process the data like DeepFashion as described in ReadMe "You can get the data follow with [PGN](https://github.com/Engineering-Course/CIHP_PGN), and re-organize the labels as you need."  But I think the segmentation results are not good in Market 1501.
I recommend this repo (https://github.com/cszy98/SPGNet) to obtain the results for Market 1501. And if you do not need the segmentation, you can find some latest pose transfer repos in (https://github.com/Zhangjinso/Awesome-pose-transfer).
