### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './fashion_data/fasion-pairs-train.csv'

### ISSUE THREAD

**Issue by Ha0Tang** [Zhangjinso/PISE#6]
Is it fasion-pairs-train.csv or fasion-resize-pairs-train.csv?

**Comment by Zhangjinso** [comment]
We use fasion-pairs-train.csv, which has the same content of fasion-resize-pairs-train.csv but a different format. You can use fasion-resize-pairs-train.csv if it works well.

**Comment by Ha0Tang** [comment]
where can I download fasion-pairs-train.csv?

**Comment by adminzwdsession** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/home/zjs/my/Pose-Transfer/fashion_data/fasion-pairs-train.csv'

**Comment by Zhangjinso** [comment]
You can download it from https://drive.google.com/drive/folders/1BX3Bxh8KG01yKWViRY0WTyDWbJHju-SL. I will update ReadMe soon.
