### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/zjs/.torch/models/vgg19-dcbb9e9d.pth'

### ISSUE THREAD

**Issue by Ha0Tang** [Zhangjinso/PISE#7]

**Comment by Zhangjinso** [comment]
You can download vgg19-dcbb9e9d.pth from https://github.com/pytorch/vision/tree/master/torchvision/models and change the related path.

**Comment by confifu** [comment]
Checkpoint is here. [https://download.pytorch.org/models/vgg19-dcbb9e9d.pth](https://download.pytorch.org/models/vgg19-dcbb9e9d.pth)
