### ISSUE TITLE
How to continue training after interruption?

### ISSUE THREAD

**Issue by Ha0Tang** [Zhangjinso/PISE#9]

**Comment by Zhangjinso** [comment]
You can refer to the options used in this work. With --continue_train and specific --which_iter (default is latest), you can continue training your model.

**Comment by Ha0Tang** [comment]
@Zhangjinso  --continue_train will start from epoch 0?

**Comment by Zhangjinso** [comment]
It is strange. If you set --continue_train, the default option of which_iter is latest (means the latest model in your specific folder).  You can  refer to line 43--45 to check this process.
